/**
 * Copyright (c) 2011 Obeo.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 * 
 */
package org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;
import org.eclipse.emf.ecore.util.InternalEList;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Actor;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ContentfwkPackage;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Event;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Service;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByBusinessServices <em>Is Resolved By Business Services</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByProcesses <em>Is Resolved By Processes</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsGeneratedByProcesses <em>Is Generated By Processes</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByActors <em>Is Resolved By Actors</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsGeneratedByActors <em>Is Generated By Actors</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class EventImpl extends ElementImpl implements Event {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return ContentfwkPackage.Literals.EVENT;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	public EList<Service> getIsResolvedByBusinessServices() {
		return (EList<Service>)eDynamicGet(ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES, ContentfwkPackage.Literals.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES, true, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	public EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> getIsResolvedByProcesses() {
		return (EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)eDynamicGet(ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES, ContentfwkPackage.Literals.EVENT__IS_RESOLVED_BY_PROCESSES, true, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	public EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> getIsGeneratedByProcesses() {
		return (EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)eDynamicGet(ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES, ContentfwkPackage.Literals.EVENT__IS_GENERATED_BY_PROCESSES, true, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	public EList<Actor> getIsResolvedByActors() {
		return (EList<Actor>)eDynamicGet(ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS, ContentfwkPackage.Literals.EVENT__IS_RESOLVED_BY_ACTORS, true, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Actor getIsGeneratedByActors() {
		return (Actor)eDynamicGet(ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, ContentfwkPackage.Literals.EVENT__IS_GENERATED_BY_ACTORS, true, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Actor basicGetIsGeneratedByActors() {
		return (Actor)eDynamicGet(ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, ContentfwkPackage.Literals.EVENT__IS_GENERATED_BY_ACTORS, false, true);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetIsGeneratedByActors(Actor newIsGeneratedByActors, NotificationChain msgs) {
		msgs = eDynamicInverseAdd((InternalEObject)newIsGeneratedByActors, ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, msgs);
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setIsGeneratedByActors(Actor newIsGeneratedByActors) {
		eDynamicSet(ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, ContentfwkPackage.Literals.EVENT__IS_GENERATED_BY_ACTORS, newIsGeneratedByActors);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByBusinessServices()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByProcesses()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsGeneratedByProcesses()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByActors()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				Actor isGeneratedByActors = basicGetIsGeneratedByActors();
				if (isGeneratedByActors != null)
					msgs = ((InternalEObject)isGeneratedByActors).eInverseRemove(this, ContentfwkPackage.ACTOR__GENERATES_EVENTS, Actor.class, msgs);
				return basicSetIsGeneratedByActors((Actor)otherEnd, msgs);
		}
		return super.eInverseAdd(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return ((InternalEList<?>)getIsResolvedByBusinessServices()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return ((InternalEList<?>)getIsResolvedByProcesses()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return ((InternalEList<?>)getIsGeneratedByProcesses()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return ((InternalEList<?>)getIsResolvedByActors()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				return basicSetIsGeneratedByActors(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return getIsResolvedByBusinessServices();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return getIsResolvedByProcesses();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return getIsGeneratedByProcesses();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return getIsResolvedByActors();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				if (resolve) return getIsGeneratedByActors();
				return basicGetIsGeneratedByActors();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				getIsResolvedByBusinessServices().clear();
				getIsResolvedByBusinessServices().addAll((Collection<? extends Service>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				getIsResolvedByProcesses().clear();
				getIsResolvedByProcesses().addAll((Collection<? extends org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				getIsGeneratedByProcesses().clear();
				getIsGeneratedByProcesses().addAll((Collection<? extends org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				getIsResolvedByActors().clear();
				getIsResolvedByActors().addAll((Collection<? extends Actor>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				setIsGeneratedByActors((Actor)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				getIsResolvedByBusinessServices().clear();
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				getIsResolvedByProcesses().clear();
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				getIsGeneratedByProcesses().clear();
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				getIsResolvedByActors().clear();
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				setIsGeneratedByActors((Actor)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return !getIsResolvedByBusinessServices().isEmpty();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return !getIsResolvedByProcesses().isEmpty();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return !getIsGeneratedByProcesses().isEmpty();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return !getIsResolvedByActors().isEmpty();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				return basicGetIsGeneratedByActors() != null;
		}
		return super.eIsSet(featureID);
	}

} //EventImpl
