/**
 * Copyright (c) 2011 Obeo.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 * 
 */
package org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectWithInverseResolvingEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Actor;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ContentfwkPackage;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Event;
import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Service;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Event</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByBusinessServices <em>Is Resolved By Business Services</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByProcesses <em>Is Resolved By Processes</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsGeneratedByProcesses <em>Is Generated By Processes</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsResolvedByActors <em>Is Resolved By Actors</em>}</li>
 *   <li>{@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.impl.EventImpl#getIsGeneratedByActors <em>Is Generated By Actors</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class EventImpl extends ElementImpl implements Event {
	/**
	 * The cached value of the '{@link #getIsResolvedByBusinessServices() <em>Is Resolved By Business Services</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsResolvedByBusinessServices()
	 * @generated
	 * @ordered
	 */
	protected EList<Service> isResolvedByBusinessServices;

	/**
	 * The cached value of the '{@link #getIsResolvedByProcesses() <em>Is Resolved By Processes</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsResolvedByProcesses()
	 * @generated
	 * @ordered
	 */
	protected EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> isResolvedByProcesses;

	/**
	 * The cached value of the '{@link #getIsGeneratedByProcesses() <em>Is Generated By Processes</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsGeneratedByProcesses()
	 * @generated
	 * @ordered
	 */
	protected EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> isGeneratedByProcesses;

	/**
	 * The cached value of the '{@link #getIsResolvedByActors() <em>Is Resolved By Actors</em>}' reference list.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsResolvedByActors()
	 * @generated
	 * @ordered
	 */
	protected EList<Actor> isResolvedByActors;

	/**
	 * The cached value of the '{@link #getIsGeneratedByActors() <em>Is Generated By Actors</em>}' reference.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @see #getIsGeneratedByActors()
	 * @generated
	 * @ordered
	 */
	protected Actor isGeneratedByActors;

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventImpl() {
		super();
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	protected EClass eStaticClass() {
		return ContentfwkPackage.Literals.EVENT;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Service> getIsResolvedByBusinessServices() {
		if (isResolvedByBusinessServices == null) {
			isResolvedByBusinessServices = new EObjectWithInverseResolvingEList.ManyInverse<Service>(Service.class, this, ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES, ContentfwkPackage.SERVICE__RESOLVES_EVENTS);
		}
		return isResolvedByBusinessServices;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> getIsResolvedByProcesses() {
		if (isResolvedByProcesses == null) {
			isResolvedByProcesses = new EObjectWithInverseResolvingEList.ManyInverse<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>(org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process.class, this, ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES, ContentfwkPackage.PROCESS__RESOLVES_EVENTS);
		}
		return isResolvedByProcesses;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process> getIsGeneratedByProcesses() {
		if (isGeneratedByProcesses == null) {
			isGeneratedByProcesses = new EObjectWithInverseResolvingEList.ManyInverse<org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>(org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process.class, this, ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES, ContentfwkPackage.PROCESS__GENERATES_EVENTS);
		}
		return isGeneratedByProcesses;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EList<Actor> getIsResolvedByActors() {
		if (isResolvedByActors == null) {
			isResolvedByActors = new EObjectWithInverseResolvingEList.ManyInverse<Actor>(Actor.class, this, ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS, ContentfwkPackage.ACTOR__RESOLVES_EVENTS);
		}
		return isResolvedByActors;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Actor getIsGeneratedByActors() {
		if (isGeneratedByActors != null && isGeneratedByActors.eIsProxy()) {
			InternalEObject oldIsGeneratedByActors = (InternalEObject)isGeneratedByActors;
			isGeneratedByActors = (Actor)eResolveProxy(oldIsGeneratedByActors);
			if (isGeneratedByActors != oldIsGeneratedByActors) {
				if (eNotificationRequired())
					eNotify(new ENotificationImpl(this, Notification.RESOLVE, ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, oldIsGeneratedByActors, isGeneratedByActors));
			}
		}
		return isGeneratedByActors;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Actor basicGetIsGeneratedByActors() {
		return isGeneratedByActors;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public NotificationChain basicSetIsGeneratedByActors(Actor newIsGeneratedByActors, NotificationChain msgs) {
		Actor oldIsGeneratedByActors = isGeneratedByActors;
		isGeneratedByActors = newIsGeneratedByActors;
		if (eNotificationRequired()) {
			ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, oldIsGeneratedByActors, newIsGeneratedByActors);
			if (msgs == null) msgs = notification; else msgs.add(notification);
		}
		return msgs;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setIsGeneratedByActors(Actor newIsGeneratedByActors) {
		if (newIsGeneratedByActors != isGeneratedByActors) {
			NotificationChain msgs = null;
			if (isGeneratedByActors != null)
				msgs = ((InternalEObject)isGeneratedByActors).eInverseRemove(this, ContentfwkPackage.ACTOR__GENERATES_EVENTS, Actor.class, msgs);
			if (newIsGeneratedByActors != null)
				msgs = ((InternalEObject)newIsGeneratedByActors).eInverseAdd(this, ContentfwkPackage.ACTOR__GENERATES_EVENTS, Actor.class, msgs);
			msgs = basicSetIsGeneratedByActors(newIsGeneratedByActors, msgs);
			if (msgs != null) msgs.dispatch();
		}
		else if (eNotificationRequired())
			eNotify(new ENotificationImpl(this, Notification.SET, ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS, newIsGeneratedByActors, newIsGeneratedByActors));
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public NotificationChain eInverseAdd(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByBusinessServices()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByProcesses()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsGeneratedByProcesses()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return ((InternalEList<InternalEObject>)(InternalEList<?>)getIsResolvedByActors()).basicAdd(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				if (isGeneratedByActors != null)
					msgs = ((InternalEObject)isGeneratedByActors).eInverseRemove(this, ContentfwkPackage.ACTOR__GENERATES_EVENTS, Actor.class, msgs);
				return basicSetIsGeneratedByActors((Actor)otherEnd, msgs);
		}
		return super.eInverseAdd(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return ((InternalEList<?>)getIsResolvedByBusinessServices()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return ((InternalEList<?>)getIsResolvedByProcesses()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return ((InternalEList<?>)getIsGeneratedByProcesses()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return ((InternalEList<?>)getIsResolvedByActors()).basicRemove(otherEnd, msgs);
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				return basicSetIsGeneratedByActors(null, msgs);
		}
		return super.eInverseRemove(otherEnd, featureID, msgs);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object eGet(int featureID, boolean resolve, boolean coreType) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return getIsResolvedByBusinessServices();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return getIsResolvedByProcesses();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return getIsGeneratedByProcesses();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return getIsResolvedByActors();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				if (resolve) return getIsGeneratedByActors();
				return basicGetIsGeneratedByActors();
		}
		return super.eGet(featureID, resolve, coreType);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@SuppressWarnings("unchecked")
	@Override
	public void eSet(int featureID, Object newValue) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				getIsResolvedByBusinessServices().clear();
				getIsResolvedByBusinessServices().addAll((Collection<? extends Service>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				getIsResolvedByProcesses().clear();
				getIsResolvedByProcesses().addAll((Collection<? extends org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				getIsGeneratedByProcesses().clear();
				getIsGeneratedByProcesses().addAll((Collection<? extends org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				getIsResolvedByActors().clear();
				getIsResolvedByActors().addAll((Collection<? extends Actor>)newValue);
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				setIsGeneratedByActors((Actor)newValue);
				return;
		}
		super.eSet(featureID, newValue);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void eUnset(int featureID) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				getIsResolvedByBusinessServices().clear();
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				getIsResolvedByProcesses().clear();
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				getIsGeneratedByProcesses().clear();
				return;
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				getIsResolvedByActors().clear();
				return;
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				setIsGeneratedByActors((Actor)null);
				return;
		}
		super.eUnset(featureID);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean eIsSet(int featureID) {
		switch (featureID) {
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_BUSINESS_SERVICES:
				return isResolvedByBusinessServices != null && !isResolvedByBusinessServices.isEmpty();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_PROCESSES:
				return isResolvedByProcesses != null && !isResolvedByProcesses.isEmpty();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_PROCESSES:
				return isGeneratedByProcesses != null && !isGeneratedByProcesses.isEmpty();
			case ContentfwkPackage.EVENT__IS_RESOLVED_BY_ACTORS:
				return isResolvedByActors != null && !isResolvedByActors.isEmpty();
			case ContentfwkPackage.EVENT__IS_GENERATED_BY_ACTORS:
				return isGeneratedByActors != null;
		}
		return super.eIsSet(featureID);
	}

} //EventImpl
