<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="representations"
    nsURI="http://www.obeonetwork.org/dsl/togaf/representations/1.0" nsPrefix="rep">
  <eClassifiers xsi:type="ecore:EClass" name="Representation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepresentationsContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="representations" upperBound="-1"
        eType="#//Representation" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
