/**
 * Copyright (c) 2011 Obeo.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     Obeo - initial API and implementation
 * 
 */
package org.obeonetwork.dsl.togaf.contentfwk.contentfwk.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.obeonetwork.dsl.togaf.contentfwk.contentfwk.util.ContentfwkAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class ContentfwkItemProviderAdapterFactory extends ContentfwkAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ContentfwkItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.EnterpriseArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnterpriseArchitectureItemProvider enterpriseArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.EnterpriseArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnterpriseArchitectureAdapter() {
		if (enterpriseArchitectureItemProvider == null) {
			enterpriseArchitectureItemProvider = new EnterpriseArchitectureItemProvider(this);
		}

		return enterpriseArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.BusinessArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessArchitectureItemProvider businessArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.BusinessArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessArchitectureAdapter() {
		if (businessArchitectureItemProvider == null) {
			businessArchitectureItemProvider = new BusinessArchitectureItemProvider(this);
		}

		return businessArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.DataArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataArchitectureItemProvider dataArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.DataArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataArchitectureAdapter() {
		if (dataArchitectureItemProvider == null) {
			dataArchitectureItemProvider = new DataArchitectureItemProvider(this);
		}

		return dataArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.TechnologyArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TechnologyArchitectureItemProvider technologyArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.TechnologyArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTechnologyArchitectureAdapter() {
		if (technologyArchitectureItemProvider == null) {
			technologyArchitectureItemProvider = new TechnologyArchitectureItemProvider(this);
		}

		return technologyArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Driver} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DriverItemProvider driverItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Driver}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDriverAdapter() {
		if (driverItemProvider == null) {
			driverItemProvider = new DriverItemProvider(this);
		}

		return driverItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Goal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GoalItemProvider goalItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Goal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGoalAdapter() {
		if (goalItemProvider == null) {
			goalItemProvider = new GoalItemProvider(this);
		}

		return goalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Objective} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ObjectiveItemProvider objectiveItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Objective}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createObjectiveAdapter() {
		if (objectiveItemProvider == null) {
			objectiveItemProvider = new ObjectiveItemProvider(this);
		}

		return objectiveItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.OrganizationUnit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected OrganizationUnitItemProvider organizationUnitItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.OrganizationUnit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createOrganizationUnitAdapter() {
		if (organizationUnitItemProvider == null) {
			organizationUnitItemProvider = new OrganizationUnitItemProvider(this);
		}

		return organizationUnitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Actor} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActorItemProvider actorItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Actor}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActorAdapter() {
		if (actorItemProvider == null) {
			actorItemProvider = new ActorItemProvider(this);
		}

		return actorItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Role} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoleItemProvider roleItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Role}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoleAdapter() {
		if (roleItemProvider == null) {
			roleItemProvider = new RoleItemProvider(this);
		}

		return roleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.DataEntity} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DataEntityItemProvider dataEntityItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.DataEntity}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDataEntityAdapter() {
		if (dataEntityItemProvider == null) {
			dataEntityItemProvider = new DataEntityItemProvider(this);
		}

		return dataEntityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalApplicationComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalApplicationComponentItemProvider logicalApplicationComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalApplicationComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalApplicationComponentAdapter() {
		if (logicalApplicationComponentItemProvider == null) {
			logicalApplicationComponentItemProvider = new LogicalApplicationComponentItemProvider(this);
		}

		return logicalApplicationComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Function} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FunctionItemProvider functionItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Function}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFunctionAdapter() {
		if (functionItemProvider == null) {
			functionItemProvider = new FunctionItemProvider(this);
		}

		return functionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.BusinessService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected BusinessServiceItemProvider businessServiceItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.BusinessService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createBusinessServiceAdapter() {
		if (businessServiceItemProvider == null) {
			businessServiceItemProvider = new BusinessServiceItemProvider(this);
		}

		return businessServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProcessItemProvider processItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Process}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProcessAdapter() {
		if (processItemProvider == null) {
			processItemProvider = new ProcessItemProvider(this);
		}

		return processItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PlatformService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlatformServiceItemProvider platformServiceItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PlatformService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlatformServiceAdapter() {
		if (platformServiceItemProvider == null) {
			platformServiceItemProvider = new PlatformServiceItemProvider(this);
		}

		return platformServiceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalTechnologyComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PhysicalTechnologyComponentItemProvider physicalTechnologyComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalTechnologyComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPhysicalTechnologyComponentAdapter() {
		if (physicalTechnologyComponentItemProvider == null) {
			physicalTechnologyComponentItemProvider = new PhysicalTechnologyComponentItemProvider(this);
		}

		return physicalTechnologyComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Product} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProductItemProvider productItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Product}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProductAdapter() {
		if (productItemProvider == null) {
			productItemProvider = new ProductItemProvider(this);
		}

		return productItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Measure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureItemProvider measureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Measure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureAdapter() {
		if (measureItemProvider == null) {
			measureItemProvider = new MeasureItemProvider(this);
		}

		return measureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ServiceQuality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ServiceQualityItemProvider serviceQualityItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ServiceQuality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createServiceQualityAdapter() {
		if (serviceQualityItemProvider == null) {
			serviceQualityItemProvider = new ServiceQualityItemProvider(this);
		}

		return serviceQualityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Contract} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContractItemProvider contractItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Contract}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContractAdapter() {
		if (contractItemProvider == null) {
			contractItemProvider = new ContractItemProvider(this);
		}

		return contractItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Event} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EventItemProvider eventItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Event}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEventAdapter() {
		if (eventItemProvider == null) {
			eventItemProvider = new EventItemProvider(this);
		}

		return eventItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Control} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ControlItemProvider controlItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Control}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createControlAdapter() {
		if (controlItemProvider == null) {
			controlItemProvider = new ControlItemProvider(this);
		}

		return controlItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Element} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ElementItemProvider elementItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Element}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createElementAdapter() {
		if (elementItemProvider == null) {
			elementItemProvider = new ElementItemProvider(this);
		}

		return elementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Container} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainerItemProvider containerItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Container}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainerAdapter() {
		if (containerItemProvider == null) {
			containerItemProvider = new ContainerItemProvider(this);
		}

		return containerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Location} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LocationItemProvider locationItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Location}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLocationAdapter() {
		if (locationItemProvider == null) {
			locationItemProvider = new LocationItemProvider(this);
		}

		return locationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Capability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CapabilityItemProvider capabilityItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Capability}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCapabilityAdapter() {
		if (capabilityItemProvider == null) {
			capabilityItemProvider = new CapabilityItemProvider(this);
		}

		return capabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Principle} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PrincipleItemProvider principleItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Principle}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPrincipleAdapter() {
		if (principleItemProvider == null) {
			principleItemProvider = new PrincipleItemProvider(this);
		}

		return principleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Constraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConstraintItemProvider constraintItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Constraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConstraintAdapter() {
		if (constraintItemProvider == null) {
			constraintItemProvider = new ConstraintItemProvider(this);
		}

		return constraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Assumption} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AssumptionItemProvider assumptionItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Assumption}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createAssumptionAdapter() {
		if (assumptionItemProvider == null) {
			assumptionItemProvider = new AssumptionItemProvider(this);
		}

		return assumptionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Requirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RequirementItemProvider requirementItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Requirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRequirementAdapter() {
		if (requirementItemProvider == null) {
			requirementItemProvider = new RequirementItemProvider(this);
		}

		return requirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Gap} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GapItemProvider gapItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.Gap}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGapAdapter() {
		if (gapItemProvider == null) {
			gapItemProvider = new GapItemProvider(this);
		}

		return gapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.WorkPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected WorkPackageItemProvider workPackageItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.WorkPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createWorkPackageAdapter() {
		if (workPackageItemProvider == null) {
			workPackageItemProvider = new WorkPackageItemProvider(this);
		}

		return workPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalDataComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalDataComponentItemProvider logicalDataComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalDataComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalDataComponentAdapter() {
		if (logicalDataComponentItemProvider == null) {
			logicalDataComponentItemProvider = new LogicalDataComponentItemProvider(this);
		}

		return logicalDataComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalDataComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PhysicalDataComponentItemProvider physicalDataComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalDataComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPhysicalDataComponentAdapter() {
		if (physicalDataComponentItemProvider == null) {
			physicalDataComponentItemProvider = new PhysicalDataComponentItemProvider(this);
		}

		return physicalDataComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ApplicationArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ApplicationArchitectureItemProvider applicationArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.ApplicationArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createApplicationArchitectureAdapter() {
		if (applicationArchitectureItemProvider == null) {
			applicationArchitectureItemProvider = new ApplicationArchitectureItemProvider(this);
		}

		return applicationArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalApplicationComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PhysicalApplicationComponentItemProvider physicalApplicationComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.PhysicalApplicationComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPhysicalApplicationComponentAdapter() {
		if (physicalApplicationComponentItemProvider == null) {
			physicalApplicationComponentItemProvider = new PhysicalApplicationComponentItemProvider(this);
		}

		return physicalApplicationComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalTechnologyComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogicalTechnologyComponentItemProvider logicalTechnologyComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.LogicalTechnologyComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogicalTechnologyComponentAdapter() {
		if (logicalTechnologyComponentItemProvider == null) {
			logicalTechnologyComponentItemProvider = new LogicalTechnologyComponentItemProvider(this);
		}

		return logicalTechnologyComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.StrategicArchitecture} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected StrategicArchitectureItemProvider strategicArchitectureItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.StrategicArchitecture}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createStrategicArchitectureAdapter() {
		if (strategicArchitectureItemProvider == null) {
			strategicArchitectureItemProvider = new StrategicArchitectureItemProvider(this);
		}

		return strategicArchitectureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.InformationSystemService} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InformationSystemServiceItemProvider informationSystemServiceItemProvider;

	/**
	 * This creates an adapter for a {@link org.obeonetwork.dsl.togaf.contentfwk.contentfwk.InformationSystemService}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInformationSystemServiceAdapter() {
		if (informationSystemServiceItemProvider == null) {
			informationSystemServiceItemProvider = new InformationSystemServiceItemProvider(this);
		}

		return informationSystemServiceItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (enterpriseArchitectureItemProvider != null) enterpriseArchitectureItemProvider.dispose();
		if (businessArchitectureItemProvider != null) businessArchitectureItemProvider.dispose();
		if (dataArchitectureItemProvider != null) dataArchitectureItemProvider.dispose();
		if (technologyArchitectureItemProvider != null) technologyArchitectureItemProvider.dispose();
		if (driverItemProvider != null) driverItemProvider.dispose();
		if (goalItemProvider != null) goalItemProvider.dispose();
		if (objectiveItemProvider != null) objectiveItemProvider.dispose();
		if (organizationUnitItemProvider != null) organizationUnitItemProvider.dispose();
		if (actorItemProvider != null) actorItemProvider.dispose();
		if (roleItemProvider != null) roleItemProvider.dispose();
		if (dataEntityItemProvider != null) dataEntityItemProvider.dispose();
		if (logicalApplicationComponentItemProvider != null) logicalApplicationComponentItemProvider.dispose();
		if (functionItemProvider != null) functionItemProvider.dispose();
		if (businessServiceItemProvider != null) businessServiceItemProvider.dispose();
		if (processItemProvider != null) processItemProvider.dispose();
		if (platformServiceItemProvider != null) platformServiceItemProvider.dispose();
		if (physicalTechnologyComponentItemProvider != null) physicalTechnologyComponentItemProvider.dispose();
		if (productItemProvider != null) productItemProvider.dispose();
		if (measureItemProvider != null) measureItemProvider.dispose();
		if (serviceQualityItemProvider != null) serviceQualityItemProvider.dispose();
		if (contractItemProvider != null) contractItemProvider.dispose();
		if (eventItemProvider != null) eventItemProvider.dispose();
		if (controlItemProvider != null) controlItemProvider.dispose();
		if (elementItemProvider != null) elementItemProvider.dispose();
		if (containerItemProvider != null) containerItemProvider.dispose();
		if (locationItemProvider != null) locationItemProvider.dispose();
		if (capabilityItemProvider != null) capabilityItemProvider.dispose();
		if (principleItemProvider != null) principleItemProvider.dispose();
		if (constraintItemProvider != null) constraintItemProvider.dispose();
		if (assumptionItemProvider != null) assumptionItemProvider.dispose();
		if (requirementItemProvider != null) requirementItemProvider.dispose();
		if (gapItemProvider != null) gapItemProvider.dispose();
		if (workPackageItemProvider != null) workPackageItemProvider.dispose();
		if (logicalDataComponentItemProvider != null) logicalDataComponentItemProvider.dispose();
		if (physicalDataComponentItemProvider != null) physicalDataComponentItemProvider.dispose();
		if (applicationArchitectureItemProvider != null) applicationArchitectureItemProvider.dispose();
		if (physicalApplicationComponentItemProvider != null) physicalApplicationComponentItemProvider.dispose();
		if (logicalTechnologyComponentItemProvider != null) logicalTechnologyComponentItemProvider.dispose();
		if (strategicArchitectureItemProvider != null) strategicArchitectureItemProvider.dispose();
		if (informationSystemServiceItemProvider != null) informationSystemServiceItemProvider.dispose();
	}

}
